In [2]:
import numpy as np

In [3]:
a=np.random.randn(2,2)

In [4]:
a

array([[ 0.11784001, -0.13606755],
       [-0.33319313,  2.33131533]])

In [5]:
a=a.reshape(1,4, )

In [6]:
a

array([[ 0.11784001, -0.13606755, -0.33319313,  2.33131533]])

In [7]:
a.ravel()

array([ 0.11784001, -0.13606755, -0.33319313,  2.33131533])

In [8]:
a.flatten()

array([ 0.11784001, -0.13606755, -0.33319313,  2.33131533])

In [9]:
arr1=np.random.randn(2,3)

In [10]:
arr2=np.random.randn(2,3)

In [11]:
arr1

array([[-2.02235154,  0.23804787,  0.09951135],
       [-0.43453529, -2.62355818, -0.43107324]])

In [12]:
arr2

array([[-0.20991088, -0.82149914,  1.08378678],
       [-2.71803782, -0.53173113,  1.53106165]])

In [13]:
np.concatenate((arr1,arr2), axis=1)

array([[-2.02235154,  0.23804787,  0.09951135, -0.20991088, -0.82149914,
         1.08378678],
       [-0.43453529, -2.62355818, -0.43107324, -2.71803782, -0.53173113,
         1.53106165]])

In [14]:
arr3=[1,2,3,4,5,6,7,8,9]

In [15]:
arr3

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
arr3=np.array(arr3)

In [17]:
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr4=np.split(arr3, [3,6])

In [19]:
arr4

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [20]:
arr4[1][2]

6

In [21]:
arr5=[[1,2,3,4,0],[5,6,7,8,9]]

In [22]:
arr5=np.array(arr5)

In [23]:
arr5.ndim

2

In [24]:
arr5.shape

(2, 5)

In [25]:
np.split(arr5, [1,2])

[array([[1, 2, 3, 4, 0]]),
 array([[5, 6, 7, 8, 9]]),
 array([], shape=(0, 5), dtype=int32)]

In [26]:
import pandas as pd

In [27]:
data=pd.Series([1,2,3,4,5])

In [28]:
data

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [29]:
data.values

array([1, 2, 3, 4, 5], dtype=int64)

In [30]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [31]:
data1=pd.Series([100, 200, 300], index=["First", "Second", "Third" ])

In [32]:
data1

First     100
Second    200
Third     300
dtype: int64

In [33]:
data1["Third"]

300

In [34]:
data2=pd.Series(["Hi", "Hello", "Bye"], index=["First", "Second", "Third" ], name="Salutations")

In [35]:
data2

First        Hi
Second    Hello
Third       Bye
Name: Salutations, dtype: object

In [36]:
 print(data1[0:3])

First     100
Second    200
Third     300
dtype: int64


In [37]:
print(data1[["First", "Second"]])

First     100
Second    200
dtype: int64


In [38]:
print(data1[data1<280])

First     100
Second    200
dtype: int64


In [39]:
result=print(data1[(data1/100)*100])

100.0   NaN
200.0   NaN
300.0   NaN
dtype: float64


In [40]:
type(result)

NoneType

In [41]:
print(data1[2])

300


In [42]:
data1=data1/5

In [43]:
data1

First     20.0
Second    40.0
Third     60.0
dtype: float64

In [44]:
import pandas as pd

In [45]:
sdata={"First":200, "Second":300, "Third":400, "GB":""}

In [46]:
tdata=pd.Series(sdata)

In [47]:
tdata

First     200
Second    300
Third     400
GB           
dtype: object

# Sources for our data to pandas series are direct, python lists, numpy arrays and python dictionaries

In [48]:
tdata.isnull()

First     False
Second    False
Third     False
GB        False
dtype: bool

In [49]:
tdata.name="List of Sales"

In [50]:
tdata

First     200
Second    300
Third     400
GB           
Name: List of Sales, dtype: object

In [51]:
tdata[0]=2000

In [52]:
tdata

First     2000
Second     300
Third      400
GB            
Name: List of Sales, dtype: object

In [53]:
import pandas as pd

In [54]:
s1=pd.Series([1,2,3,4,5])

In [55]:
s2=pd.Series([11,12,13,14,15])

In [56]:
data={"Apples":s1, "Oranges":s2}

In [57]:
df=pd.DataFrame(data)

In [58]:
df

Apples  Oranges
0       1       11
1       2       12
2       3       13
3       4       14
4       5       15

In [59]:
import pandas as pd
data1={"State": ["KP", "Punjab", "Sindh", "Balochistan", "GB"],
    "Budget": [200, 1200, 600, 150, 80],
    
      }

In [60]:
df2=pd.DataFrame(data1,index=['1st', '2nd', '3rd', '4th', '5th'])

In [61]:
df2

State  Budget
1st           KP     200
2nd       Punjab    1200
3rd        Sindh     600
4th  Balochistan     150
5th           GB      80

In [62]:
df2.head

<bound method NDFrame.head of            State  Budget
1st           KP     200
2nd       Punjab    1200
3rd        Sindh     600
4th  Balochistan     150
5th           GB      80>

In [63]:
df2.columns

Index(['State', 'Budget'], dtype='object')

In [64]:
df2.index

Index(['1st', '2nd', '3rd', '4th', '5th'], dtype='object')

In [65]:
df2["Budget"]

1st     200
2nd    1200
3rd     600
4th     150
5th      80
Name: Budget, dtype: int64

# Attribute type acces

In [66]:
df2.Budget

1st     200
2nd    1200
3rd     600
4th     150
5th      80
Name: Budget, dtype: int64

# Locating items by row index

In [68]:
df2.loc['3rd']

State     Sindh
Budget      600
Name: 3rd, dtype: object

In [69]:
df2.head()

State  Budget
1st           KP     200
2nd       Punjab    1200
3rd        Sindh     600
4th  Balochistan     150
5th           GB      80

# data frame video 22

In [71]:
df2.columns

Index(['State', 'Budget'], dtype='object')

In [72]:
df2.index

Index(['1st', '2nd', '3rd', '4th', '5th'], dtype='object')